### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by addeps3** [karolherbst/nouveau#2]
Hi. 
I'm interested in trying this nouveau module but am hitting some bumps. Right now during compilation.

> $ make
> make -C /lib/modules/4.8.15-ARCH/source M=/home/adam/kplr/nouveau/drm/nouveau KCPPFLAGS="-Iinclude/uapi/drm" modules
> make[1]: Entering directory '/home/adam/bk/linux48'
>   CC [M]  /home/adam/kplr/nouveau/drm/nouveau/nvif/object.o
>   CC [M]  /home/adam/kplr/nouveau/drm/nouveau/nvif/client.o
>   CC [M]  /home/adam/kplr/nouveau/drm/nouveau/nvif/device.o
>   CC [M]  /home/adam/kplr/nouveau/drm/nouveau/nvif/driver.o
>   CC [M]  /home/adam/kplr/nouveau/drm/nouveau/nvif/mem.o
>   CC [M]  /home/adam/kplr/nouveau/drm/nouveau/nvif/mmu.o
>   CC [M]  /home/adam/kplr/nouveau/drm/nouveau/nvif/notify.o
>   CC [M]  /home/adam/kplr/nouveau/drm/nouveau/nvif/vmm.o
>   CC [M]  /home/adam/kplr/nouveau/drm/nouveau/nvkm/core/client.o
>   CC [M]  /home/adam/kplr/nouveau/drm/nouveau/nvkm/core/engine.o
>   CC [M]  /home/adam/kplr/nouveau/drm/nouveau/nvkm/core/enum.o
>   CC [M]  /home/adam/kplr/nouveau/drm/nouveau/nvkm/core/event.o
>   CC [M]  /home/adam/kplr/nouveau/drm/nouveau/nvkm/core/firmware.o
>   CC [M]  /home/adam/kplr/nouveau/drm/nouveau/nvkm/core/gpuobj.o
> In file included from /home/adam/kplr/nouveau/drm/nouveau/include/nvkm/core/gpuobj.h:3:0,
>                  from /home/adam/kplr/nouveau/drm/nouveau/nvkm/core/gpuobj.c:24:
> /home/adam/kplr/nouveau/drm/nouveau/include/nvkm/core/memory.h:10:2: error: unknown type name ‘refcount_t’
>   refcount_t refcount;
>   ^~~~~~~~~~
> make[2]: *** [scripts/Makefile.build:290: /home/adam/kplr/nouveau/drm/nouveau/nvkm/core/gpuobj.o] Error 1
> make[1]: *** [Makefile:1473: _module_/home/adam/kplr/nouveau/drm/nouveau] Error 2
> make[1]: Leaving directory '/home/adam/bk/linux48'
> make: *** [Makefile:18: modules] Error 2

**Comment by karolherbst** [comment]
you have to compile against a newer kernel

**Comment by addeps3** [comment]
omg, thought it was the other way around.
underway.

**Comment by addeps3** [comment]
we'll close this issue due to user error

have a great day
